config/routes.rb
Rails.application.routes.draw do
 
  
  resources :courses do
    member do
        get 'result'
    end
  	resources :students 
  	resources :evaluations 
  end
  get 'home/index'
  root 'courses#index'
  devise_for :users, :only => [ :sessions]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  default_scope {order('date ASC')}
  belongs_to :course
  has_many :grades, inverse_of: :evaluation, dependent: :restrict_with_error 
  accepts_nested_attributes_for :grades
  validates :min_grade , presence: true,  numericality: { greater_than: 0}
  validates :title , presence: true, uniqueness: {scope: :course , message:"La evaliacion debe ser única por curso"}
  validates :date, presence: true
  validate :validates_date

  	def validates_date
  		if self.date.present?
  			if self.date.year < self.course.year then
  				errors.add(:date,"La fecha de la evaliación debe ser igual o postarior a la del curso")
  			end
  		end
  	end
	def approved_students
		 self.grades.where("grade >= #{min_grade}" ).count
	end
	def disapproved_students
		self.grades.count - self.approved_students - self.absent_sudents
	end
	def absent_sudents
		self.grades.where("grade is NULL" ).count
	end
	def percentage_of_approved
		((self.approved_students / (grades.count - self.absent_sudents).to_f) * 100).to_f.round(2)
	end
	def result student
		res=self.grades.where("student_id = #{student.id}" )
		(res.empty?)? nil : res.first.grade
	end
	def approved student
		if result(student).nil?
			false
		else
			(self.result(student)>= self.min_grade)? true : false
		end	 	 
	end
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :set_course
  before_action :set_evaluation, only: [:show, :edit, :update, :destroy]
  before_action :set_grades, only: [:show]
  # GET /evaluations
  # GET /evaluations.json
  def index
    @evaluations = @course.evaluations
  end

  # GET /evaluations/1
  # GET /evaluations/1.json
  def show
  end

  # GET /evaluations/new
  def new
    @evaluation = @course.evaluations.new
    @course.students.each do |student| 
          @evaluation.grades.build(:student=> student)       
    end
  end

  # GET /evaluations/1/edit
  def edit
  end

  # POST /evaluations
  # POST /evaluations.json
  def create
   
     
    @evaluation = @course.evaluations.new(evaluation_params)
    respond_to do |format|
      if @evaluation.save
        format.html { redirect_to  course_evaluation_path(@course,@evaluation) , notice: 'La evaluación fue creada con éxito.' }
        format.json { render :show, status: :created, location: @evaluation }
      else
        format.html { render :new }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1
  # PATCH/PUT /evaluations/1.json
  def update
    respond_to do |format|
      
      if @evaluation.update(evaluation_params)
        if params[:evaluation][:grades_attributes].present?
          @evaluation.set_grade=true
          @evaluation.save
        end
        format.html { redirect_to course_evaluation_path(@course,@evaluation), notice: 'La evaluación fue actualizada con éxito.' }
        format.json { render :show, status: :ok, location: @evaluation }
      else
         if params[:evaluation][:grades_attributes].present?
          format.html { render :show }
          format.json { render json: @evaluation.errors, status: :unprocessable_entity }
        else
          format.html { render :edit }
          format.json { render json: @evaluation.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /evaluations/1
  # DELETE /evaluations/1.json
  def destroy
    respond_to do |format|
      if @evaluation.destroy
        format.html { redirect_to course_evaluations_path(@course), notice: 'La evaluación fue eliminada con éxito.' }
        format.json { head :no_content }
      else
        format.html { render :show }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = @course.evaluations.find(params[:id])
     # @evaluation = Evaluation.find(params[:id])
    end
    def set_course
      @course = Course.find(params[:course_id])
    end
    def set_grades
      @course.students.each {|a| @evaluation.grades.find_or_create_by(student_id:a.id,evaluation_id:@evaluation.id)}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluation_params
      params.require(:evaluation).permit(:title, :min_grade, :date, :course_id, grades_attributes: [:id, :grade,:student,:evaluation, :_destroy])
    end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/evaluations/_evaluation.html.erb
        <td><%= evaluation.title %></td>
        <td><%= evaluation.min_grade %></td>
        <td><%= evaluation.date %></td>
        <td><%= evaluation.course %></td>
        <td><%= link_to 'Show', evaluation %></td>
        <td><%= link_to 'Edit', edit_evaluation_path(evaluation) %></td>
        <td><%= link_to 'Destroy', evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/evaluations/_form.html.erb
<%= form_with(model: [ @course, evaluation ], local: true) do |form| %>
 <% if evaluation.errors.any? %>
    <div id="error_explanation">
      <h2>Error</h2>
      <ul>
      <% evaluation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :evaluation_title, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :min_grade %>
    <%= form.text_field :min_grade, id: :evaluation_min_grade, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :date %>
    <%= form.date_select :date, id: :evaluation_date, :class => "form-control" %>
  </div>

 

  <div class="actions form-group">
    <%= form.submit "Crear evaluación", :class => "btn btn-primary btn-form" %>
  </div>
<% end %>

app/views/evaluations/_set_grades.html.erb
<%= form_for [@course,@evaluation] do |f| %>
  <h3 style="color: white; text-align: center">Grades</h3>
  <table  class="table table-bordered table-light gradesTable table-striped">
    <tr>
      <th >Nombre</th>
      <th >Dni</th>
      <th>Legajo</th>
      <th >Nota</th>
    </tr>
    <%= f.fields_for :grades do |grades_form| %>
    <tr>
      <td >      
        <%= grades_form.object.student.name %>
      </td>
       <td >      
        <%= grades_form.object.student.dni %>
      </td>
      <td >      
        <%= grades_form.object.student.number %>
      </td>
      <td>
        <% if @evaluation.set_grade %>
           
            <%= grades_form.text_field :grade, placeholder: "Ausente"  %>
          
        <%else%>
          <%= grades_form.text_field :grade  %>
        <% end %>
      </td>
    </tr>
    <% end %>

  </table>
  <div class="action offset-md-5">
  <%= f.submit "Actualizar" ,class:"btn btn-primary btn-form" %>
  </div>
<% end %>

app/views/evaluations/edit.html.erb
<h1>Editing Evaluation</h1>

<%= render 'form', evaluation: @evaluation %>

<%= link_to 'Show', course_evaluation_path(@course,@evaluation) ,:class => "btn btn-primary btn-form" %>
<%= link_to 'Back', course_evaluations_path(@course),:class => "btn btn-primary btn-form" %>
<%= link_to 'Ir al curso', @course, :class => "btn btn-primary btn-form" %>

app/views/evaluations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Evaluaciones de <%= @course.name %> del año  <%= @course.year %> </h1>

<table class="table table-bordered table-light gradesTable table-striped ">
  <thead>
    <tr>
      <th>Title</th>
      <th>Min grade</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>
        
  <tbody>
    <% @evaluations.each do |evaluation| %>
      <tr>
        <td><%= evaluation.title %></td>
        <td><%= evaluation.min_grade %></td>
        <td><%= evaluation.date %></td>
        <td><%= link_to 'Ver evaluación', course_evaluation_path(@course,evaluation) %></td>
        <td><%= link_to  edit_course_evaluation_path(@course,evaluation)  do%>
          <%= content_tag :i,"", :class => "fa fa-edit" %>
            <% end %>
        </td>
        <td><%= link_to course_evaluation_path(@course,evaluation), method: :delete, data: { confirm: 'Estas seguro?' } do %>
          <%= content_tag :i,"", :class => "fa fa-trash" %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva evaluación', new_course_evaluation_path(@course), class: "btn btn-primary btn-form" %>
<%= link_to 'Volver al curso', @course, class: "btn btn-primary btn-form" %>

app/views/evaluations/new.html.erb
<h1 class="title-courses">Nueva Evaluación</h1>
<div class="offset-md-5 col-md-4 form-signin ">
<%= render 'form', evaluation: @evaluation %>

<%= link_to 'Volver', course_evaluations_path(@course), :class => "btn btn-primary btn-form" %>
<%= link_to 'Ir al curso', @course, :class => "btn btn-primary btn-form" %>
</div>

app/views/evaluations/show.html.erb
<div class="container  div-inline2">
  <% if @evaluation.errors.any? %>
    <ul>
      <% @evaluation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
  <table class="table table-bordered table-light gradesTable table-striped">
    <tr>
      <th>Titulo</th>
      <th>Nota minima</th>
      <th>Fecha</th>
      <th>Aprobados</th>
      <th>Desaprobados</th>
      <th>Ausentes</th>
      <th>Porcentaje de aprobados</th>
    </tr>
    <tr>
      <td><%= @evaluation.title %></td>
      <td><%= @evaluation.min_grade %></td>
      <td><%= @evaluation.date %></td>
      <% if @evaluation.set_grade %>
        <td><%= @evaluation.approved_students%></td>
        <td><%= @evaluation.disapproved_students%></td>
        <td><%= @evaluation.absent_sudents %></td>
        <td><%= @evaluation.percentage_of_approved %></td>
      <%else%> 
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
      <%end%>
    </tr>
  </table>

<br>
<%= link_to 'Editar', edit_course_evaluation_path(@course,@evaluation),class:"btn btn-primary btn-form" %> 
<%= link_to 'Volver', course_evaluations_path,class:"btn btn-primary btn-form" %>
<%= link_to 'Ir al curso', @course, :class => "btn btn-primary btn-form" %>
<%= link_to 'Estudiantes', course_students_path(@course), :class => "btn btn-primary btn-form" %>




<input class="btn btn-primary btn-form" id="actualizarNotas" type="button" value="Ver/Actualizar notas" onclick="showmydiv()">
<input  class="btn btn-primary btn-form" id="ocultarNotas" type="button" value="Ocultar notas" onclick="hidemydiv()" style="display: none">
<div id="myBox" style="display:none">
<% if !@evaluation.grades.empty? %>
<div class="container">
  <%= render 'set_grades', evaluation: @evaluation %>
</div>
<%end%>
</div>